name: 🤖 Telegram Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Qo'lda ishga tushirish imkoniyati
  schedule:
    # Har 9 daqiqada ishga tushadi (GitHub limiti - max 10 daqiqa)
    - cron: '*/9 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 8  # 8 daqiqadan keyin avtomatik to'xtaydi
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: 🚀 Run Telegram Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      run: |
        echo "🤖 Bot ishga tushmoqda..."
        python bot.py
